package edu.orangecoastcollege.cs272.nutritioneffex.view;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Label;

import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;

public class AlternateMainMenuController implements Initializable {
	@FXML
	private Label DietaryRestrictionsButton;
	@FXML
	private Label NutritionCalculatorButton;
	@FXML
	private Label FindYourOlympicAthleteButton;
	@FXML
	private Label LogOffButton;
	@FXML
	private Label UpdateAccountInfoButton;
	@FXML
	private ImageView backgroundImage;

	// Event Listener on Label[#DietaryRestrictionsButton].onMouseClicked
	@FXML
	public void loadDietaryRestrictionsMenu(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Label[#NutritionCalculatorButton].onMouseClicked
	@FXML
	public void loadNutritionCalculatorMenu(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Label[#FindYourOlympicAthleteButton].onMouseClicked
	@FXML
	public void loadOlympicAthletesMenu(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Label[#LogOffButton].onMouseClicked
	@FXML
	public void logOff(MouseEvent event) {
		System.out.println("CLICKED");
		
	}
	// Event Listener on Label[#LogOffButton].onMouseEntered
	@FXML
	public void scaleUp(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Label[#LogOffButton].onMouseExited
	@FXML
	public void scaleDown(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Label[#UpdateAccountInfoButton].onMouseClicked
	@FXML
	public void loadUpdateAccountInfoScene(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#backgroundImage].onMouseClicked
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		System.out.println("LOADED");
		
	}
	
}
