package edu.orangecoastcollege.cs272.nutritioneffex.view;

import java.net.URL;
import java.util.ResourceBundle;

import edu.orangecoastcollege.cs272.nutritioneffex.controller.Controller;
import javafx.animation.FadeTransition;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.TextField;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;
import javafx.util.Duration;

/**
 * Controller for the CalorieCalculator view that allows a user to retrieve their
 * recommended daily caloric intake. The information is then stored in a relational database
 * under the users ID.
 * @author brendendrew
 * 
 */
public class CalorieCalculatorController extends SeamlessViewFX implements Initializable {
	
	Controller controller = Controller.getInstance();
	public FadeTransition fadeOut = new FadeTransition(Duration.millis(3000));
	@FXML
	private ImageView backgroundImage;
	@FXML
	private Label calculateButton;
	@FXML
	private TextField weightTF;
	@FXML
	private Label incorrectInfoLabel;
	@FXML
	private ImageView backButton;
	@FXML
	private TextField heightTF;
	
	@SuppressWarnings("rawtypes")
	@FXML
	private ComboBox goalWeightCB;
	
	@FXML
	private TextField recommendedIntake;

	// Event Listener on Label[#calculateButton].onMouseClicked
	@FXML
	public void calculate(MouseEvent event) 
	{
		if (heightTF.getText().isEmpty() || weightTF.getText().isEmpty()) 
		{
			incorrectInfoLabel.setText("missing fields");
			incorrectInfoLabel.setVisible(true);
			fadeOut.setNode(incorrectInfoLabel);
			fadeOut.setFromValue(1.0);
			fadeOut.setToValue(0.0);
	    	fadeOut.setCycleCount(1);
	    	fadeOut.setAutoReverse(false);
	    	fadeOut.playFromStart();
			return;
		}
		double heightInCM = Double.parseDouble(heightTF.getText());
		double age = (double) controller.getCurrentUser().getAge();
		double result = 10 + (6.25 * heightInCM) - (5 * age + 5);
		
		switch (goalWeightCB.getSelectionModel().getSelectedIndex())
		{
		// lose weight
		case 0: 
			result-=500;
			break;
		// gain weight
		case 1:
			result += 500;
			break;
		default:
		// maintain weight
			break;
		}
		
		recommendedIntake.setText(String.valueOf(result + 1000));
		recommendedIntake.setVisible(true);
		incorrectInfoLabel.setVisible(false);
		// Adds caloric intake to database to store history
		controller.addCaloricIntake(result);
		
		// TODO Autogenerated
	}
	
	
	// Event Listener on ImageView[#backButton].onMouseClicked
	@FXML
	public void backToCalculatorMenu(MouseEvent event) 
	{
		ViewNavigator.loadScene("Calculator Menu", ViewNavigator.CALCULATOR_MENU_SCENE);
	}
	
	
	@SuppressWarnings("unchecked")
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		
		goalWeightCB.setItems(controller.getGoalWeights());
		incorrectInfoLabel.setVisible(false);
		
		try {
			backButton.setStyle(NORMAL_SCALE);
			backButton.setOnMouseEntered(e -> backButton.setStyle(SCALE_UP));
			backButton.setOnMouseExited(e -> backButton.setStyle(NORMAL_SCALE));
			
		}
		catch (NullPointerException e) {
			System.out.println("Transferring scenes");
		}
		

		
	}
	

}
