package edu.orangecoastcollege.cs272.nutritioneffex.view;

import javafx.fxml.FXML;

import javafx.scene.control.Button;
import edu.orangecoastcollege.cs272.sdowdle.capstone.controller.Controller;
import javafx.event.ActionEvent;
import javafx.scene.control.ListView;
import javafx.scene.input.MouseEvent;

public class FavoriteFoodsScene 
{
	private static Controller controller = Controller.getInstance();
	
	@FXML
	private Button backButton;
	@FXML
	private ListView favoriteFoodsLV;
	@FXML
	private Button deleteButton;
	@FXML
	private Button viewDetailsButton;

	// Event Listener on Button[#backButton].onAction
	@FXML
	public void loadDRMainMenu(ActionEvent event) 
	{
		ViewNavigator.loadScene("Dietary Restictions", ViewNavigator.DR_MAIN_MENU_SCENE);
	}
	// Event Listener on ListView[#favoriteFoodsLV].onMouseClicked
	@FXML
	public void selectFood(MouseEvent event) 
	{
		// TODO Autogenerated
	}
	// Event Listener on Button[#deleteButton].onAction
	@FXML
	public void deleteFavoriteFood(ActionEvent event) 
	{
		// TODO Autogenerated
	}
	// Event Listener on Button[#viewDetailsButton].onAction
	@FXML
	public void loadFoodDetailsScene(ActionEvent event) 
	{
		// TODO Autogenerated
	}
}
