package edu.orangecoastcollege.cs272.nutritioneffex.view;

import javafx.fxml.FXML;
import edu.orangecoastcollege.cs272.sdowdle.capstone.controller.Controller;
import javafx.event.ActionEvent;

import javafx.scene.input.MouseEvent;

public class FoodScene
{
	private static Controller controller = Controller.getInstance();
	// Event Listener on ListView.onMouseClicked
	@FXML
	public void selectFood(MouseEvent event) 
	{
		// TODO Autogenerated
	}
	// Event Listener on CheckBox.onAction
	@FXML
	public void filterExcludedItems(ActionEvent event) 
	{
		// TODO Autogenerated
	}
	// Event Listener on CheckBox.onAction
	@FXML
	public void unfilter(ActionEvent event)
	{
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void addToFavoriteFoods(ActionEvent event)
	{
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void loadDRMainMenu(ActionEvent event) 
	{
		ViewNavigator.loadScene("Dietary Restictions", ViewNavigator.DR_MAIN_MENU_SCENE);
	}
}
