package edu.orangecoastcollege.cs272.nutritioneffex.view;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.input.MouseEvent;

public class MainMenuSceneController {
	@FXML
	private Button DietaryMainMenuButton;
	@FXML
	private Button CalculatorsButton;
	@FXML
	private Button OlympicAthleticButton;
	@FXML
	private Button UpdateAccountInfoButton;
	@FXML
	private Button llogOffButton;

	// Event Listener on Button[#CalculatorsButton].onMouseClicked
	@FXML
	public void loadCalculators(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#OlympicAthleticButton].onMouseClicked
	@FXML
	public void openOlympicPotential(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#llogOffButton].onMouseDragged
	@FXML
	public void logOff(MouseEvent event) {
		// TODO Autogenerated
	}
}
