package edu.orangecoastcollege.cs272.nutritioneffex.view;

import java.net.URL;
import java.util.ResourceBundle;

import javax.sound.midi.ControllerEventListener;

import edu.orangecoastcollege.cs272.nutritioneffex.controller.Controller;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.ListView;
import javafx.scene.control.TextField;

import javafx.scene.input.MouseEvent;

public class OlympicAthleticPotentialSceneController implements Initializable{
	
	Controller controller = Controller.getInstance();
	@FXML
	private TextField heightTF;
	@FXML
	private TextField weightTF;
	@FXML
	private Button MatchButton;
	@FXML
	private Button backButton;
	@FXML
	private ListView listview;

	// Event Listener on Button[#MatchButton].onMouseClicked
	@FXML
	public void match(MouseEvent event) {
		// TODO Autogenerated
		 double inkg,inmeters;
    double Weight = Double.parseDouble(weightTF.getText());
		   //1 lb = 0.453592 kg
		    inkg = Weight*.45359;
		    
		    //1 inch = 0.0254 meters.
		    double Height = Double.parseDouble(heightTF.getText());
		    inmeters = Height*.0254;
		    
		    
		    //Margin of error
		  /*  OlympiansList = controller.filterathlete(b -> ( b.getWeight() < (inkg + 4)
		    		&& b.getWeight()> (inkg - 4) 
		    		&& b.getHeight() >(inmeters-0.2) 
		    		&& b.getHeight() <(inmeters+ 0.2 )));
		           
		    //reset the LV
		    OlympiansLV.setItems(OlympiansList);
	
	*/
	}
	// Event Listener on Button[#backButton].onMouseClicked
	@FXML
	public void back(MouseEvent event) {
		ViewNavigator.loadScene("Main Menu", ViewNavigator.ALTERNATE_MAIN_MENU_SCENE);
	}
	@SuppressWarnings("unchecked")
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		//listview.setItems(Controller.getAllOlympiansList());
		
	}
}
